_BASE_: "Base-SparseInst.yaml"
MODEL:
  SPARSE_INST:
    ENCODER:
      IN_FEATURES: ["Hd8", "Hd16", "Hd32"]
  BACKBONE:
    FREEZE_AT: 0
    NAME: "van_b1"
  VAN: 
    drop_rate: 0
    drop_path_rate: 0.2
    depths: [2, 2, 4, 2]
    init_cfg: [{'type':'Pretrained', 'checkpoint':'pretrained/van_b1.pth'}]
    # norm_cfg: {'type':'SyncBN', 'requires_grad':True}
OUTPUT_DIR: "output/sparse_inst_van_giam"

SOLVER:
  # IMS_PER_BATCH: 96
  # MAX_ITER: 180000
  BASE_LR: 0.00005
  STEPS: (210000, 250000)